apiVersion: v1
kind: ConfigMap
metadata:
  name: calculator-config
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_TTL: "30"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "calculatordb"
  POSTGRES_USER: "calcuser"